# Generated by Django 3.2.9 on 2021-11-09 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_articlecategory_category_comment_follow_like'),
    ]

    operations = [
        migrations.RenameModel('ArticleCategory', 'PostCategory'),
    ]
